name: Quality CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Download code
      uses: actions/checkout@v4

    - name: Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: NPM
      run: npm ci –ignore-scripts

    - name: Linter
      run: npm run lint

    - name: Tests
      run: npm test
